apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backstage-configmap.yaml

patches:
  - path: deployment-patch.yaml

helmCharts:
  - name: backstage
    repo: https://backstage.github.io/charts
    version: 2.6.3
    releaseName: backstage
    namespace: backstage
    valuesInline:
      service:
        type: ClusterIP
      extraAppConfig:
        - filename: app-config.extra.yaml
          configMapRef: backstage-config
