apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kyverno
    repo: https://kyverno.github.io/kyverno/
    version: 3.1.4
    releaseName: kyverno
    namespace: kyverno
    valuesInline:
      installCRDs: true
      admissionController:
        replicas: 1
        containerPort: 9443

resources:
  - policies.yaml
